alias: KNMI Weercode Automatisering
description: Automatisering voor KNMI-weercodes (groen, geel, oranje, rood)
triggers:
  - entity_id:
      - sensor.knmi_weercode
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.knmi_weercode
            state: groen
        sequence:
          - data:
              name: default
              mode: dark
            action: frontend.set_theme
      - conditions:
          - condition: state
            entity_id: sensor.knmi_weercode
            state: geel
        sequence:
          - data:
              name: knmicodegeel
              mode: dark
            action: frontend.set_theme
      - conditions:
          - condition: state
            entity_id: sensor.knmi_weercode
            state: oranje
        sequence:
          - data:
              name: knmicodeoranje
              mode: dark
            action: frontend.set_theme
      - conditions:
          - condition: state
            entity_id: sensor.knmi_weercode
            state: rood
        sequence:
          - data:
              name: knmicoderood
              mode: dark
            action: frontend.set_theme
    default: []
mode: single
