version: '3.9'

services:

  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WHISPER_MODEL=large-v3
      - WHISPER_LANG=nl
    volumes:
      - ./whisper-data:/config
    ports:
      - "10300:10300"
    restart: unless-stopped

  piper:
    image: rhasspy/wyoming-piper:latest
    container_name: piper
    command: ["--voice", "nl_BE-nathalie-medium"]
    volumes:
      - ./piper/data:/data
    ports:
      - "10200:10200"
    restart: unless-stopped

  openwakeword:
    image: rhasspy/wyoming-openwakeword:latest
    container_name: openwakeword
    command: ["--custom-model-dir", "/data"]
    volumes:
      - ./openwakeword:/data
    ports:
      - "10400:10400"
    restart: unless-stopped




