version: '3.9'

services:

  whisper:
    image: rhasspy/wyoming-whisper:latest
    container_name: whisper
    command: ["--model", "large-v3", "--language", "nl"]
    volumes:
      - ./whisper-data:/data
      - ./whisper-cache:/root/.cache/whisper
    ports:
      - "10300:10300"
    restart: unless-stopped

  piper:
    image: rhasspy/wyoming-piper:latest
    container_name: piper
    command: ["--voice", "nl_BE-nathalie-medium"]
    volumes:
      - ./piper/data:/data
    ports:
      - "10200:10200"
    restart: unless-stopped

  openwakeword:
    image: rhasspy/wyoming-openwakeword:latest
    container_name: openwakeword
    command: ["--custom-model-dir", "/data"]
    volumes:
      - ./openwakeword:/data
    ports:
      - "10400:10400"
    restart: unless-stopped




