alias: View-assist-p2000 auto vlaardingen-rijnmond
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_boolean.p2000
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.p2000
            state: "on"
        sequence:
          - action: automation.turn_on
            target:
              entity_id: automation.view_assist_p2000
            data: {}
          - action: automation.turn_off
            target:
              entity_id: automation.p2000_rijnmond
            data:
              stop_actions: true
      - conditions:
          - condition: state
            entity_id: input_boolean.p2000
            state: "off"
        sequence:
          - action: automation.turn_off
            target:
              entity_id: automation.view_assist_p2000
            data:
              stop_actions: true
          - action: automation.turn_on
            target:
              entity_id: automation.p2000_rijnmond
            data: {}
mode: single
