alias: view-assist - p2000
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.p2000
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.oneplus12_charger_type
        state: wireless
actions:
  - action: chime_tts.say
    metadata: {}
    data:
      chime_path: chirp
    target:
      entity_id: media_player.tablet
  - action: browser_mod.navigate
    metadata: {}
    data:
      browser_id:
        - 0041739398d895e9040c07be4dc364d8
      path: /dashboard-viewassist/p2000
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - action: browser_mod.navigate
    metadata: {}
    data:
      browser_id:
        - 0041739398d895e9040c07be4dc364d8
      path: /dashboard-viewassist/map
mode: single
