////This go in your configuration.yaml/////

template:
  - sensor:
      - name: "Hoogste pollenwaarde Bomen"
        unique_id: hoogste_pollen_bomen
        state: >
          {% set bomen = state_attr('sensor.kleenex_pollen_radar_pollen_bomen', 'details') %}
          {% if bomen %}
            {% set hoogste = bomen | sort(attribute='value', reverse=True) | first %}
            {{ hoogste.value }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "ppm"

      - name: "Hoogste pollenbron Bomen"
        unique_id: hoogste_pollenbron_bomen
        state: >
          {% set bomen = state_attr('sensor.kleenex_pollen_radar_pollen_bomen', 'details') %}
          {% if bomen %}
            {% set hoogste = bomen | sort(attribute='value', reverse=True) | first %}
            {{ hoogste.name }}
          {% else %}
            "Onbekend"
          {% endif %}

      - name: "Hoogste pollenwaarde Gras"
        unique_id: hoogste_pollen_gras
        state: >
          {% set grassen = state_attr('sensor.kleenex_pollen_radar_pollen_gras', 'details') %}
          {% if grassen %}
            {% set hoogste = grassen | sort(attribute='value', reverse=True) | first %}
            {{ hoogste.value }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "ppm"

      - name: "Hoogste pollenbron Gras"
        unique_id: hoogste_pollenbron_gras
        state: >
          {% set grassen = state_attr('sensor.kleenex_pollen_radar_pollen_gras', 'details') %}
          {% if grassen %}
            {% set hoogste = grassen | sort(attribute='value', reverse=True) | first %}
            {{ hoogste.name }}
          {% else %}
            "Onbekend"
          {% endif %}

      - name: "Hoogste pollenwaarde Kruiden"
        unique_id: hoogste_pollen_kruiden
        state: >
          {% set kruiden = state_attr('sensor.kleenex_pollen_radar_pollen_kruiden', 'details') %}
          {% if kruiden %}
            {% set hoogste = kruiden | sort(attribute='value', reverse=True) | first %}
            {{ hoogste.value }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "ppm"

      - name: "Hoogste pollenbron Kruiden"
        unique_id: hoogste_pollenbron_kruiden
        state: >
          {% set kruiden = state_attr('sensor.kleenex_pollen_radar_pollen_kruiden', 'details') %}
          {% if kruiden %}
            {% set hoogste = kruiden | sort(attribute='value', reverse=True) | first %}
            {{ hoogste.name }}
          {% else %}
            "Onbekend"
          {% endif %}

