////This go in your configuration.yaml/////

template:
  - sensor:
      - name: "Hoogste pollenwaarde Gras"
        unique_id: hoogste_pollen_gras
        state: >
          {% set gras = {'details': [{'name': 'Gras', 'value': states('sensor.kleenex_pollen_radar_pollen_gras') | int }]} %}
          {% set hoogste = gras.details | sort(attribute='value', reverse=True) | first %}
          {{ hoogste.value }}
        unit_of_measurement: "ppm"

      - name: "Hoogste pollenbron Gras"
        unique_id: hoogste_pollenbron_gras
        state: >
          {% set gras = {'details': [{'name': 'Gras', 'value': states('sensor.kleenex_pollen_radar_pollen_gras') | int }]} %}
          {% set hoogste = gras.details | sort(attribute='value', reverse=True) | first %}
          {{ hoogste.name }}

      - name: "Hoogste pollenwaarde Kruiden"
        unique_id: hoogste_pollen_kruiden
        state: >
          {% set kruiden = {'details': [{'name': 'Kruiden', 'value': states('sensor.kleenex_pollen_radar_pollen_kruiden') | int }]} %}
          {% set hoogste = kruiden.details | sort(attribute='value', reverse=True) | first %}
          {{ hoogste.value }}
        unit_of_measurement: "ppm"

      - name: "Hoogste pollenbron Kruiden"
        unique_id: hoogste_pollenbron_kruiden
        state: >
          {% set kruiden = {'details': [{'name': 'Kruiden', 'value': states('sensor.kleenex_pollen_radar_pollen_kruiden') | int }]} %}
          {% set hoogste = kruiden.details | sort(attribute='value', reverse=True) | first %}
          {{ hoogste.name }}

      - name: "Hoogste pollenwaarde Bomen"
        unique_id: hoogste_pollen_bomen
        state: >
          {% set bomen = state_attr('sensor.kleenex_pollen_radar_pollen_bomen', 'current')['details'] %}
          {% set hoogste = bomen | sort(attribute='value', reverse=True) | first %}
          {{ hoogste.value }}
        unit_of_measurement: "ppm"

      - name: "Hoogste pollenbron Bomen"
        unique_id: hoogste_pollenbron_bomen
        state: >
          {% set bomen = state_attr('sensor.kleenex_pollen_radar_pollen_bomen', 'current')['details'] %}
          {% set hoogste = bomen | sort(attribute='value', reverse=True) | first %}
          {{ hoogste.name }}
